#pragma once

#define TAPPING_TERM_PER_KEY
#define TAPPING_FORCE_HOLD_PER_KEY
#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 5000
#define ENCODERS_PAD_A { D3 }
#define ENCODERS_PAD_B { D2 }
#define MK_KINETIC_SPEED
#define MOUSEKEY_INTERVAL 40
#define MOUSEKEY_MOVE_DELTA 6
#define MOUSEKEY_INITIAL_SPEED 80
#define MOUSEKEY_ACCELERATED_SPEED 4000