#pragma once
#define ALT_ESC A(KC_ESC)
#define LSA_ESC LSA(KC_ESC)
#define ALT_TAB TD(ALT_TABLE)
#define ALTSTAB TD(ALT_SHIFT_TABLE)
#define ALT_LYS TD(ALT_LAYERS)
#define KC_INSP TD(INSERT_PLUS)

#define KC_ESCG LGUI_T(KC_ESC)
#define KC_TABG RGUI_T(KC_TAB)
#define ALTLBRC LT(0, KC_LBRC)
#define CTLRBRC LT(0, KC_RBRC)

#define OS_LSFT OSM(MOD_LSFT)
#define OS_RSFT OSM(MOD_RSFT)
#define OS_L_FN OSL(_FN)

#define MK_TAB  LT(_MK, KC_TAB)
#define MK_BSPC LT(_MK, KC_BSPC)
#define MK_DEL  LT(_MK, KC_DEL)
#define FS_ENT  LT(0, KC_ENT)
#define FS_BSPC LT(0, KC_BSPC)
#define FN_SPC  LT(_FN, KC_SPC)
#define FC_MINS LT(0, KC_MINS)
#define FA_EQL  LT(0, KC_EQL)

#define ST_PENT LSFT_T(KC_PENT)
#define ST_ENT  LSFT_T(KC_ENT)

#define NEW_TAB C(KC_T)
#define CLS_TAB C(KC_W)
#define PRV_TAB C(KC_PGUP)
#define NXT_TAB C(KC_PGDN)
#define PRV_WIN LCA(KC_LEFT)
#define NXT_WIN LCA(KC_RIGHT)
#define PRV_PG  C(S(KC_PGUP))
#define NXT_PG  C(S(KC_PGDN))
