#pragma once
#define ALT_TAB TD(ALT_TABLE)
#define ALT_LYS TD(ALT_LAYERS)
#define CPY_PST TD(COPY_PASTE_LAYERSLOCK)
#define INS_SHT TD(INSERT_SCREENSHOT_LAYERS)

#define GUI_ESC LGUI_T(KC_ESC)
#define OS_LSFT OSM(MOD_LSFT)
#define OS_RSFT OSM(MOD_RSFT)
#define OS_L_FN OSL(_FN)

#define MK_TAB  LT(_MK, KC_TAB)
#define MK_BSPC  LT(_MK, KC_BSPC)
#define FN_ENT  LT(0, KC_ENT)
#define FN_SPC  LT(_FN, KC_SPC)
#define FN_MINS LT(0, KC_MINS)
#define FN_EQL  LT(0, KC_EQL)

#define ALT_ESC A(KC_ESC)
#define NEW_TAB C(KC_T)
#define CLS_TAB C(KC_W)
#define PRV_TAB C(KC_PGUP)
#define NXT_TAB C(KC_PGDN)
#define PRV_WIN LCA(KC_LEFT)
#define NXT_WIN LCA(KC_RIGHT)
#define PRV_PG  C(S(KC_PGUP))
#define NXT_PG  C(S(KC_PGDN))